---
- hosts: 172.31.33.16
  become: yes
  tasks:
  - name: i want install direct linux command
    command: hostname -f
    register: my1stresult

  - name: i want to display first task result
    debug: 
       msg: "{{my1stresult}}"
