---
- hosts: all
  become: yes
  tasks:
  - name: i want ping all nodes
    ping:

  - name: i want to install apache on ansible nodes
    apt:
      name: apache2
      state: present

  - name: i want to install tree on ansible nodes
    apt:
      name: tree
      state: present

  - name: i want to install wget on ansible nodes
    apt:
      name: wget
      state: present    
