---
- hosts: 172.31.33.16
  become: yes
  tasks:
  - include: myfile.yml
  - name: i want to install webserver
    apt:
      name: apache2
      state: present

 # - name: copy index file into the node file
  #  copy:
   #   sre: myindexpage
    #  dest: /var/www/html/index.html  
   # notify: restartwebserver   

  - name: copy dynamic file into node
    template:
        src: mydynoindex.j2
        dest:  /var/www/html/index.html
    notify: restartwebserver  

  - name: download internet files
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/-tomcat-1apache0.0.20.tar.gz
      dest: /home/badri/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes    

  handlers:
  - name: restartwebserver
    service:
        name: apache2
        state: started     
